coinbase:
  secret: secret
  key: key
  passphrase: passphrase
  baseCurrency: USD

amount: 100

coins:
  - { ticker: BTC, percentage: 30 }
  - { ticker: ETH, percentage: 50 }
  - { ticker: ZEC, percentage: 20 }
