coinbase:
  # API secret, key and passphrase can be created at https://pro.coinbase.com/profile/api
  secret: secret
  key: key
  passphrase: passphrase

# Valid cron tab format
# "@hourly", "@daily", "@weekly", "@monthly", or
# custom cron schedule (See https://crontab.guru)
schedule: "@daily"

# List of coins to purchase and the percentage weight for
# how likely to purchase any of them at the scheduled time,
# the base currency to purchase them with and
# the amount in the base currency to purchase
#
# Note: Percentages should add up to 100%
coins:
  - { ticker: ETH, percentage: 60, baseCurrency: USD, amount: 10 }
  - { ticker: BTC, percentage: 40, baseCurrency: USD, amount: 10 }
